
/*Para cambiar la estructura de las tablas siempre utilizamos la instrucción ALTER TABLE*/

/*SON UNICAMENTE EJEMPLOS DE INSTRUCCIONES PERO LOS CAMBIOS REALIZADOS CON EL ALTER NO SERVIRIAN PARA MEJORARLA EN ESTE CASO*/

/*AÑADIR UNA COLUMNA --> */ALTER TABLE PASAJERO ADD Edad TINYINT UNSIGNED;

/*BORRAR UNA COLUMNA -->*/ALTER TABLE PASAJERO DROP Edad;

/*AÑADIR UNA PROPIEDAD (en ambos utilizamos el MODIFY para cambiar las características y tipo de dato de la columna)--> */ ALTER TABLE COMPAÑIA MODIFY Logo BLOB;

ALTER TABLE COMPAÑIA MODIFY Nombre VARCHAR(20) UNIQUE;


/*AÑADIR Y BORRAR PRIMARY Y FOREIGN KEY*/

ALTER TABLE TERMINALES DROP PRIMARY KEY;

ALTER TABLE TERMINALES ADD PRIMARY KEY(Número,CodOACI_AEROPUERTO);

ALTER TABLE ASIENTO DROP FOREIGN KEY FK_VUELO_ASIENTO;

ALTER TABLE ASIENTO ADD CONSTRAINT FK_VUELO_ASIENTO FOREIGN KEY(CodVuelo) REFERENCES VUELO(CodVuelo);




